"""updated group

Revision ID: 3079936c41c6
Revises: a5486ac74fbc
Create Date: 2023-06-11 18:03:09.691211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3079936c41c6'
down_revision = 'a5486ac74fbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_owner_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('groups_owner_id_fkey', 'groups', 'users', ['owner_id'], ['user_id'])
    # ### end Alembic commands ###
