"""enlarged password

Revision ID: 57ae20f827d4
Revises: 6e7c2711a3c0
Create Date: 2022-11-06 20:35:37.081132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57ae20f827d4'
down_revision = '6e7c2711a3c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=False)
    # ### end Alembic commands ###
