"""reconfiguring first commit

Revision ID: 6e7c2711a3c0
Revises: ad98c804ec03
Create Date: 2022-11-06 19:30:05.225733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e7c2711a3c0'
down_revision = 'ad98c804ec03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('memberships_ibfk_1', 'memberships', type_='foreignkey')
    op.drop_constraint('purchases_ibfk_1', 'purchases', type_='foreignkey')
    op.drop_table('groups_')
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_foreign_key(None, 'memberships', 'groups', ['group_id'], ['group_id'])
    op.create_foreign_key(None, 'purchases', 'groups', ['group_id'], ['group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key('purchases_ibfk_1', 'purchases', 'groups_', ['group_id'], ['group_id'])
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key('memberships_ibfk_1', 'memberships', 'groups_', ['group_id'], ['group_id'])
    op.create_table('groups_',
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], name='groups__ibfk_1'),
    sa.PrimaryKeyConstraint('group_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('groups')
    # ### end Alembic commands ###
