"""adding_membership_status

Revision ID: 7bef68dcd1dc
Revises: f7027f460bde
Create Date: 2022-11-11 12:31:40.133905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bef68dcd1dc'
down_revision = 'f7027f460bde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'groups', ['secret_key'])
    op.add_column('memberships', sa.Column('status', sa.Enum('UNACCEPTED', 'ACCEPTED', 'BANNED', name='userstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'status')
    op.drop_constraint(None, 'groups', type_='unique')
    # ### end Alembic commands ###
