"""renamed_group_password

Revision ID: f7027f460bde
Revises: 57ae20f827d4
Create Date: 2022-11-10 22:38:29.743840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7027f460bde'
down_revision = '57ae20f827d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('secret_key', sa.String(length=45), nullable=False))
    op.drop_column('groups', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=False))
    op.drop_column('groups', 'secret_key')
    # ### end Alembic commands ###
